spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/insurance?serverTimezone=Europe/Bratislava&useSSL=false}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/dev
spring.flyway.validate-on-migrate=true

xsd.schema.path=src/main/resources/xsd/

spring.activemq.broker-url=tcp://localhost:61616

#Logging ----------------------------------------------------------#
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.com.insurance=DEBUG

#logging.level.org.flywaydb=DEBUG
#logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
